[package]
name = "pact-stub-server"
version = "0.7.1"
edition = "2024"
authors = ["Ronald Holshausen <ronald.holshausen@gmail.com>"]
description = "Standalone pact stub server"
homepage = "https://www.pact.io"
repository = "https://github.com/pact-foundation/pact-stub-server"
readme = "README.md"
keywords = ["cdc", "pact", "testing"]
license = "MIT"
exclude = ["*.iml"]

[dependencies]
anyhow = "1"
base64 = "0.22"
bytes = "1"
clap = { version = "4", features = ["cargo", "env", "std"] }
futures = "0.3"
http = "1"
http-body-util = { version = "0.1", features = ["full"] }
httpdate = "1"
hyper = { version = "1", features = ["full"] }
hyper-util = { version = "0.1", features = ["full"] }
itertools = "0.14"
maplit = "1"
mimalloc = "0.1"
notify = "8"
notify-debouncer-mini = "0.7"
pact_matching = "2"
pact_models = "1"
pact_verifier = "1"
regex = "1"
reqwest = { version = "0.13", default-features = false, features = [
  "http2",
  "json",
  "rustls"
] }
serde_json = "1"
tokio = { version = "1", features = ["full"] }
tower = { version = "0.5", features = ["full"] }
tower-http = { version = "0.6", features = ["full"] }
tower-service = { version = "0.3" }
tracing = { version = "0.1", features = ["log"] }
tracing-core = "0.1"
tracing-subscriber = "0.3"

[dev-dependencies]
env_logger = "0.11"
expectest = "0.12"
pretty_assertions = "1"
test-log = "0.2"
trycmd = "1"

[profile.release]
# https://doc.rust-lang.org/stable/rustc/codegen-options/
# https://doc.rust-lang.org/rustc/profile-guided-optimization.html
# https://github.com/johnthagen/min-sized-rust
opt-level = "z"
strip = true
lto = true
codegen-units = 1
